#include "strings.h"
#include <string.h>

static BtnUiLang g_lang = BTN_LANG_EN;

/* Reihenfolge muss exakt zu BtnStringId in strings.h passen - ein Kommentar
 * pro Zeile waere hier mehr Rauschen als Nutzen, die Spalten sprechen fuer
 * sich (jede Zeile = eine Sprache, jede Spalte = ein BTN_STR_*). Nicht-ASCII
 * Zeichen stehen als rohes UTF-8 direkt im Quelltext (wie in shim.m) statt
 * als \x-Escapes: \x-Escapes verschlucken beliebig viele folgende Hex-Ziffern
 * (nicht nur zwei!), sodass z.B. "\xc3\x9cber" durch das folgende 'b' zu
 * "\xc3" + "\x9cb" (ausserhalb des char-Wertebereichs) zusammengezogen wird -
 * ein klassischer C-Stolperstein, der hier zu Compile-Fehlern fuehrte. */
static const char *const g_strings[BTN_LANG_COUNT][BTN_STR_COUNT] = {
    /* BTN_LANG_EN */
    {
        "About ", "Quit ", "File", "New", "Open...", "Open Recent", "(None)",
        "Save", "Save As...", "Close", "Print...", "Edit", "Undo", "Redo",
        "Cut", "Copy", "Paste", "Select All", "Find & Replace...", "Untitled",
        "Do you want to save the changes made to “%s”?",
        "Your changes will be lost if you don't save them.",
        "Save", "Don't Save", "Cancel",
        "Find:", "Replace:", "Not found",
        "%d replaced",
        "Match %d of %d",
        "Help", "Keyboard Shortcuts...", "Keyboard Shortcuts",
        "⌘N — New\n⌘O — Open\n⌘S — Save\n⇧⌘S — Save As\n⌘W — Close\n⌘Z — Undo\n⇧⌘Z — Redo\n⌘X — Cut\n⌘C — Copy\n⌘V — Paste\n⌘A — Select All\n⌘F — Find & Replace\n⌘L — Go to Line\n⌘+/⌘- — Zoom In/Out\n⌘0 — Actual Size\n⌥←/→ — Jump by word\n⌘←/→ — Line start/end\nTab / ⇧Tab — Indent / outdent lines (Tab: selection over several lines)\n⌘G / ⇧⌘G — Find next / previous\n⌘E — Use selection for find\n⌃Tab or ⇧⌘] / ⇧⌘[ — Next / previous tab\n⌘M — Minimize, ⌃⌘F — Full screen\nEsc — Close find bar\nReturn (search field) — Next match\n⇧Return (search field) — Previous match\nReturn (replace field) — Replace + Next\n⌘Return (replace field) — Replace All\n\\t (find/replace field, regex mode) — Tab character",
        "Replace All",
        "“%s” may not be a text file.",
        "This file appears to contain binary data. Editing and saving it could corrupt it.",
        "Open Anyway",
        "Go to Line...",
        "Line number (1–%d):",
        "OK",
        "View",
        "Zoom In",
        "Zoom Out",
        "Actual Size",
        "No live search – press Return",
        "Line %zu, Column %zu",
        "%zu lines | %zu words | %zu characters | UTF-8",
        "“%s” could not be opened.",
        "The file could not be read.",
        "The file is larger than %d MB, the maximum size BTNEdit can open.",
        "“%s” could not be saved.",
        "Check that the folder exists and that you have write permission. Your changes are still open.",
        "Line Endings",
        "LF – macOS/Unix",
        "CRLF – Windows",
        "CR – Classic Mac OS",
        "%s (mixed)",
        "Find Next",
        "Find Previous",
        "Use Selection for Find",
        "Window",
        "Minimize",
        "Zoom",
        "Enter Full Screen",
        "Show Next Tab",
        "Show Previous Tab",
        "“%s” was changed by another application.",
        "Reloading replaces the text in BTNEdit with the version on disk. Your unsaved changes will be lost.",
        "Reload",
        "Keep My Version",
        "“%s” has been changed by another application since it was opened or last saved.",
        "Saving will overwrite those changes.",
        "Save Anyway",
        "BTNEdit quit unexpectedly.",
        "Unsaved changes to %d document(s) were found. Restore them now? Discarding cannot be undone.",
        "Restore",
        "Discard"
    },
    /* BTN_LANG_DE */
    {
        "Über ", "Beende ", "Ablage", "Neu", "Öffnen...",
        "Zuletzt geöffnet", "(Keine)",
        "Sichern", "Sichern unter...", "Schließen", "Drucken...",
        "Bearbeiten", "Widerrufen", "Wiederholen",
        "Ausschneiden", "Kopieren", "Einfügen", "Alles auswählen",
        "Suchen und Ersetzen...", "Unbenannt",
        "Möchtest du die Änderungen an „%s“ sichern?",
        "Deine Änderungen gehen verloren, wenn du sie nicht sicherst.",
        "Sichern", "Nicht sichern", "Abbrechen",
        "Suchen:", "Ersetzen:", "Nicht gefunden",
        "%d ersetzt",
        "Treffer %d von %d",
        "Hilfe", "Tastenkürzel...", "Tastenkürzel",
        "⌘N — Neu\n⌘O — Öffnen\n⌘S — Sichern\n⇧⌘S — Sichern unter\n⌘W — Schließen\n⌘Z — Widerrufen\n⇧⌘Z — Wiederholen\n⌘X — Ausschneiden\n⌘C — Kopieren\n⌘V — Einfügen\n⌘A — Alles auswählen\n⌘F — Suchen und Ersetzen\n⌘L — Gehe zu Zeile\n⌘+/⌘- — Vergrößern/Verkleinern\n⌘0 — Tatsächliche Größe\n⌥←/→ — Wortsprung\n⌘←/→ — Zeilenanfang/-ende\nTab / ⇧Tab — Zeilen ein-/ausrücken (Tab: Selektion über mehrere Zeilen)\n⌘G / ⇧⌘G — Weitersuchen / rückwärts suchen\n⌘E — Auswahl für Suche verwenden\n⌃Tab oder ⇧⌘] / ⇧⌘[ — Nächster / vorheriger Tab\n⌘M — Im Dock ablegen, ⌃⌘F — Vollbild\nEsc — Suchleiste schließen\nReturn (Suchfeld) — Nächster Treffer\n⇧Return (Suchfeld) — Voriger Treffer\nReturn (Ersetzen-Feld) — Ersetzen + Weiter\n⌘Return (Ersetzen-Feld) — Alle ersetzen\n\\t (Suchen-/Ersetzen-Feld, Regex-Modus) — Tabulator",
        "Alle ersetzen",
        "„%s“ ist möglicherweise keine Textdatei.",
        "Diese Datei scheint binäre Daten zu enthalten. Bearbeiten und Sichern könnten sie beschädigen.",
        "Trotzdem öffnen",
        "Gehe zu Zeile...",
        "Zeilennummer (1–%d):",
        "OK",
        "Darstellung",
        "Vergrößern",
        "Verkleinern",
        "Tatsächliche Größe",
        "Keine Live-Suche – Return",
        "Zeile %zu, Spalte %zu",
        "%zu Zeilen | %zu Wörter | %zu Zeichen | UTF-8",
        "„%s“ konnte nicht geöffnet werden.",
        "Die Datei konnte nicht gelesen werden.",
        "Die Datei ist größer als %d MB – das ist die maximale Größe, die BTNEdit öffnen kann.",
        "„%s“ konnte nicht gesichert werden.",
        "Prüfe, ob der Ordner existiert und du Schreibrechte hast. Deine Änderungen sind weiterhin geöffnet.",
        "Zeilenenden",
        "LF – macOS/Unix",
        "CRLF – Windows",
        "CR – klassisches Mac OS",
        "%s (gemischt)",
        "Weitersuchen",
        "Rückwärts suchen",
        "Auswahl für Suche verwenden",
        "Fenster",
        "Im Dock ablegen",
        "Zoomen",
        "Vollbildmodus aktivieren",
        "Nächsten Tab zeigen",
        "Vorherigen Tab zeigen",
        "„%s“ wurde von einem anderen Programm geändert.",
        "Neu laden ersetzt den Text in BTNEdit durch die Version auf der Festplatte. Deine ungesicherten Änderungen gehen dabei verloren.",
        "Neu laden",
        "Meine Version behalten",
        "„%s“ wurde seit dem Öffnen oder letzten Sichern von einem anderen Programm geändert.",
        "Sichern überschreibt diese Änderungen.",
        "Trotzdem sichern",
        "BTNEdit wurde unerwartet beendet.",
        "Es gibt ungesicherte Änderungen an %d Dokument(en). Jetzt wiederherstellen? Verwerfen lässt sich nicht rückgängig machen.",
        "Wiederherstellen",
        "Verwerfen"
    },
    /* BTN_LANG_FR */
    {
        "À propos de ", "Quitter ", "Fichier", "Nouveau", "Ouvrir...",
        "Ouvrir un élément récent", "(Aucun)",
        "Enregistrer", "Enregistrer sous...", "Fermer", "Imprimer...",
        "Édition", "Annuler", "Rétablir",
        "Couper", "Copier", "Coller", "Tout sélectionner",
        "Rechercher et remplacer...", "Sans titre",
        "Voulez-vous enregistrer les modifications apportées à « %s » ?",
        "Vos modifications seront perdues si vous ne les enregistrez pas.",
        "Enregistrer", "Ne pas enregistrer", "Annuler",
        "Rechercher :", "Remplacer :", "Introuvable",
        "%d remplacement(s)",
        "Correspondance %d sur %d",
        "Aide", "Raccourcis clavier...", "Raccourcis clavier",
        "⌘N — Nouveau\n⌘O — Ouvrir\n⌘S — Enregistrer\n⇧⌘S — Enregistrer sous\n⌘W — Fermer\n⌘Z — Annuler\n⇧⌘Z — Rétablir\n⌘X — Couper\n⌘C — Copier\n⌘V — Coller\n⌘A — Tout sélectionner\n⌘F — Rechercher et remplacer\n⌘L — Aller à la ligne\n⌘+/⌘- — Zoom avant/arrière\n⌘0 — Taille réelle\n⌥←/→ — Saut de mot\n⌘←/→ — Début/fin de ligne\nTab / ⇧Tab — Indenter / désindenter (Tab : sélection sur plusieurs lignes)\n⌘G / ⇧⌘G — Rechercher le suivant / précédent\n⌘E — Utiliser la sélection pour la recherche\n⌃Tab ou ⇧⌘] / ⇧⌘[ — Onglet suivant / précédent\n⌘M — Placer dans le Dock, ⌃⌘F — Plein écran\nÉchap — Fermer la barre de recherche\nRetour (champ de recherche) — Occurrence suivante\n⇧Retour (champ de recherche) — Occurrence précédente\nRetour (champ de remplacement) — Remplacer + suivant\n⌘Retour (champ de remplacement) — Tout remplacer\n\\t (champ de recherche/remplacement, mode regex) — Tabulation",
        "Tout remplacer",
        "« %s » n'est peut-être pas un fichier texte.",
        "Ce fichier semble contenir des données binaires. Le modifier et l'enregistrer pourrait l'endommager.",
        "Ouvrir quand même",
        "Aller à la ligne...",
        "Numéro de ligne (1–%d) :",
        "OK",
        "Présentation",
        "Zoom avant",
        "Zoom arrière",
        "Taille réelle",
        "Recherche : touche Retour",
        "Ligne %zu, colonne %zu",
        "%zu lignes | %zu mots | %zu caractères | UTF-8",
        "Impossible d’ouvrir « %s ».",
        "Le fichier n’a pas pu être lu.",
        "Le fichier dépasse %d Mo, la taille maximale que BTNEdit peut ouvrir.",
        "Impossible d’enregistrer « %s ».",
        "Vérifiez que le dossier existe et que vous avez le droit d’écriture. Vos modifications restent ouvertes.",
        "Fins de ligne",
        "LF – macOS/Unix",
        "CRLF – Windows",
        "CR – Mac OS classique",
        "%s (mixte)",
        "Rechercher le suivant",
        "Rechercher le précédent",
        "Utiliser la sélection pour la recherche",
        "Fenêtre",
        "Placer dans le Dock",
        "Réduire/agrandir",
        "Passer en mode plein écran",
        "Afficher l’onglet suivant",
        "Afficher l’onglet précédent",
        "« %s » a été modifié par une autre application.",
        "Recharger remplace le texte dans BTNEdit par la version sur le disque. Vos modifications non enregistrées seront perdues.",
        "Recharger",
        "Garder ma version",
        "« %s » a été modifié par une autre application depuis son ouverture ou le dernier enregistrement.",
        "L’enregistrement écrasera ces modifications.",
        "Enregistrer quand même",
        "BTNEdit s’est fermé de manière inattendue.",
        "Des modifications non enregistrées de %d document(s) ont été trouvées. Les restaurer maintenant ? L’abandon est irréversible.",
        "Restaurer",
        "Abandonner"
    },
    /* BTN_LANG_ES */
    {
        "Acerca de ", "Salir de ", "Archivo", "Nuevo", "Abrir...",
        "Abrir reciente", "(Ninguno)",
        "Guardar", "Guardar como...", "Cerrar", "Imprimir...",
        "Edición", "Deshacer", "Rehacer",
        "Cortar", "Copiar", "Pegar", "Seleccionar todo",
        "Buscar y reemplazar...", "Sin título",
        "¿Quieres guardar los cambios realizados en “%s”?",
        "Tus cambios se perderán si no los guardas.",
        "Guardar", "No guardar", "Cancelar",
        "Buscar:", "Reemplazar:", "No encontrado",
        "%d reemplazos",
        "Coincidencia %d de %d",
        "Ayuda", "Atajos de teclado...", "Atajos de teclado",
        "⌘N — Nuevo\n⌘O — Abrir\n⌘S — Guardar\n⇧⌘S — Guardar como\n⌘W — Cerrar\n⌘Z — Deshacer\n⇧⌘Z — Rehacer\n⌘X — Cortar\n⌘C — Copiar\n⌘V — Pegar\n⌘A — Seleccionar todo\n⌘F — Buscar y reemplazar\n⌘L — Ir a la línea\n⌘+/⌘- — Acercar/Alejar\n⌘0 — Tamaño real\n⌥←/→ — Salto de palabra\n⌘←/→ — Inicio/fin de línea\nTab / ⇧Tab — Sangrar / quitar sangría (Tab: selección de varias líneas)\n⌘G / ⇧⌘G — Buscar siguiente / anterior\n⌘E — Usar selección para buscar\n⌃Tab o ⇧⌘] / ⇧⌘[ — Pestaña siguiente / anterior\n⌘M — Minimizar, ⌃⌘F — Pantalla completa\nEsc — Cerrar barra de búsqueda\nIntro (campo de búsqueda) — Siguiente coincidencia\n⇧Intro (campo de búsqueda) — Coincidencia anterior\nIntro (campo de reemplazo) — Reemplazar + siguiente\n⌘Intro (campo de reemplazo) — Reemplazar todo\n\\t (campo de búsqueda/reemplazo, modo regex) — Tabulador",
        "Reemplazar todo",
        "“%s” puede no ser un archivo de texto.",
        "Este archivo parece contener datos binarios. Editarlo y guardarlo podría dañarlo.",
        "Abrir de todos modos",
        "Ir a la línea...",
        "Número de línea (1–%d):",
        "Aceptar",
        "Vista",
        "Acercar",
        "Alejar",
        "Tamaño real",
        "Búsqueda: pulsa Intro",
        "Línea %zu, columna %zu",
        "%zu líneas | %zu palabras | %zu caracteres | UTF-8",
        "No se pudo abrir “%s”.",
        "No se pudo leer el archivo.",
        "El archivo supera los %d MB, el tamaño máximo que BTNEdit puede abrir.",
        "No se pudo guardar “%s”.",
        "Comprueba que la carpeta existe y que tienes permiso de escritura. Tus cambios siguen abiertos.",
        "Finales de línea",
        "LF – macOS/Unix",
        "CRLF – Windows",
        "CR – Mac OS clásico",
        "%s (mixto)",
        "Buscar siguiente",
        "Buscar anterior",
        "Usar selección para buscar",
        "Ventana",
        "Minimizar",
        "Zoom",
        "Entrar en pantalla completa",
        "Mostrar pestaña siguiente",
        "Mostrar pestaña anterior",
        "«%s» fue modificado por otra aplicación.",
        "Recargar reemplaza el texto de BTNEdit por la versión del disco. Se perderán los cambios no guardados.",
        "Recargar",
        "Mantener mi versión",
        "«%s» fue modificado por otra aplicación desde que se abrió o se guardó por última vez.",
        "Guardar sobrescribirá esos cambios.",
        "Guardar de todos modos",
        "BTNEdit se cerró inesperadamente.",
        "Se encontraron cambios sin guardar en %d documento(s). ¿Restaurarlos ahora? Descartarlos no se puede deshacer.",
        "Restaurar",
        "Descartar"
    },
    /* BTN_LANG_ZH (Simplified) */
    {
        "关于", "退出", "文件",
        "新建", "打开…",
        "打开最近使用的文件",
        "（无）",
        "存储", "存储为…",
        "关闭", "打印…",
        "编辑", "撤销", "重做",
        "剪切", "拷贝", "粘贴",
        "全选", "查找和替换…", "未命名",
        "要存储对“%s”的修改吗？",
        "如果不存储，你所做的修改将丢失。",
        "存储", "不存储", "取消",
        "查找:", "替换:", "未找到",
        "已替换 %d 处",
        "第 %d/%d 个匹配项",
        "帮助", "键盘快捷键…", "键盘快捷键",
        "⌘N — 新建\n⌘O — 打开\n⌘S — 存储\n⇧⌘S — 存储为\n⌘W — 关闭\n⌘Z — 撤销\n⇧⌘Z — 重做\n⌘X — 剪切\n⌘C — 拷贝\n⌘V — 粘贴\n⌘A — 全选\n⌘F — 查找和替换\n⌘L — 跳转到行\n⌘+/⌘- — 放大/缩小\n⌘0 — 实际大小\n⌥←/→ — 按词跳转\n⌘←/→ — 行首/行尾\nTab / ⇧Tab — 增加/减少缩进（Tab：选中多行时）\n⌘G / ⇧⌘G — 查找下一个 / 上一个\n⌘E — 用所选内容查找\n⌃Tab 或 ⇧⌘] / ⇧⌘[ — 下一个 / 上一个标签页\n⌘M — 最小化，⌃⌘F — 全屏幕\nEsc — 关闭查找栏\n回车（查找框）— 下一个匹配项\n⇧回车（查找框）— 上一个匹配项\n回车（替换框）— 替换并查找下一个\n⌘回车（替换框）— 全部替换\n\\t（查找/替换框，正则模式）— 制表符",
        "全部替换",
        "“%s”可能不是文本文件。",
        "该文件似乎包含二进制数据。编辑并存储可能会损坏它。",
        "仍要打开",
        "跳转到行…",
        "行号 (1–%d)：",
        "确定",
        "显示",
        "放大",
        "缩小",
        "实际大小",
        "按回车键搜索",
        "第 %zu 行，第 %zu 列",
        "%zu 行 | %zu 词 | %zu 字符 | UTF-8",
        "无法打开“%s”。",
        "无法读取该文件。",
        "文件大于 %d MB，超出了 BTNEdit 可打开的最大大小。",
        "无法存储“%s”。",
        "请检查文件夹是否存在以及您是否有写入权限。您的更改仍保持打开状态。",
        "换行符",
        "LF – macOS/Unix",
        "CRLF – Windows",
        "CR – 经典 Mac OS",
        "%s（混合）",
        "查找下一个",
        "查找上一个",
        "用所选内容查找",
        "窗口",
        "最小化",
        "缩放",
        "进入全屏幕",
        "显示下一个标签页",
        "显示上一个标签页",
        "“%s”已被其他应用程序修改。",
        "重新载入会用磁盘上的版本替换 BTNEdit 中的文本，未存储的更改将会丢失。",
        "重新载入",
        "保留我的版本",
        "自打开或上次存储以来，“%s”已被其他应用程序修改。",
        "存储将覆盖这些更改。",
        "仍然存储",
        "BTNEdit 意外退出。",
        "发现 %d 个文稿有未存储的更改。现在恢复吗？丢弃后无法撤销。",
        "恢复",
        "丢弃"
    }
};

void btn_strings_set_language(BtnUiLang lang) {
    if (lang >= 0 && lang < BTN_LANG_COUNT) {
        g_lang = lang;
    }
}

const char *btn_tr(BtnStringId id) {
    return g_strings[g_lang][id];
}

BtnUiLang btn_strings_lang_from_code(const char *code) {
    if (!code) {
        return BTN_LANG_EN;
    }
    if (strncmp(code, "de", 2) == 0) {
        return BTN_LANG_DE;
    }
    if (strncmp(code, "fr", 2) == 0) {
        return BTN_LANG_FR;
    }
    if (strncmp(code, "es", 2) == 0) {
        return BTN_LANG_ES;
    }
    if (strncmp(code, "zh", 2) == 0) {
        return BTN_LANG_ZH;
    }
    return BTN_LANG_EN;
}
